-- Run this file in the Supabase SQL editor.

create table if not exists public.entry_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  subject text not null,
  details text not null,
  author text not null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.entry_posts
  add column if not exists user_id uuid references auth.users(id) on delete set null;

create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  student text not null,
  overall int not null,
  physics int not null,
  chemistry int not null,
  biology int not null,
  mathematics int not null,
  gk int not null,
  created_at timestamptz not null default now()
);

alter table public.entry_posts enable row level security;
alter table public.leaderboard_scores enable row level security;

-- Public read is allowed so students can view shared materials.
drop policy if exists "Public read entry posts" on public.entry_posts;
create policy "Public read entry posts"
  on public.entry_posts for select
  using (true);

drop policy if exists "Public insert entry posts" on public.entry_posts;
drop policy if exists "Authenticated insert own entry posts" on public.entry_posts;
create policy "Authenticated insert own entry posts"
  on public.entry_posts for insert
  with check (auth.uid() = user_id);

drop policy if exists "Owners update own entry posts" on public.entry_posts;
create policy "Owners update own entry posts"
  on public.entry_posts for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Owners delete own entry posts" on public.entry_posts;
create policy "Owners delete own entry posts"
  on public.entry_posts for delete
  using (auth.uid() = user_id);

drop policy if exists "Public read leaderboard scores" on public.leaderboard_scores;
create policy "Public read leaderboard scores"
  on public.leaderboard_scores for select
  using (true);

-- Optional seed rows for leaderboard.
insert into public.leaderboard_scores
  (student, overall, physics, chemistry, biology, mathematics, gk)
values
  ('Nana Kofi Asare', 92, 95, 90, 88, 94, 93),
  ('Ama Serwaa Boateng', 89, 86, 92, 91, 87, 90),
  ('Kwame Owusu Mensah', 87, 89, 85, 84, 92, 86)
on conflict do nothing;
