-- Run this file in the Supabase SQL editor.

create table if not exists public.entry_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null,
  subject text not null,
  details text not null,
  author text not null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.entry_posts
  add column if not exists user_id uuid references auth.users(id) on delete set null;

create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  student text not null,
  overall int not null,
  physics int not null,
  chemistry int not null,
  biology int not null,
  mathematics int not null,
  gk int not null,
  created_at timestamptz not null default now()
);

create table if not exists public.practice_day_subject_notes (
  id bigint generated by default as identity primary key,
  day_id text not null,
  subject text not null,
  title text not null,
  details text not null,
  author text not null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.practice_day_subject_notes
  add column if not exists user_id uuid references auth.users(id) on delete set null;

alter table public.practice_day_subject_notes
  add column if not exists answer text;

alter table public.practice_day_subject_notes
  add column if not exists solution text;

alter table public.entry_posts enable row level security;
alter table public.leaderboard_scores enable row level security;
alter table public.practice_day_subject_notes enable row level security;

-- Public read is allowed so students can view shared materials.
drop policy if exists "Public read entry posts" on public.entry_posts;
create policy "Public read entry posts"
  on public.entry_posts for select
  using (true);

drop policy if exists "Public insert entry posts" on public.entry_posts;
drop policy if exists "Authenticated insert own entry posts" on public.entry_posts;
create policy "Authenticated insert own entry posts"
  on public.entry_posts for insert
  with check (auth.uid() = user_id);

drop policy if exists "Owners update own entry posts" on public.entry_posts;
create policy "Owners update own entry posts"
  on public.entry_posts for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Owners delete own entry posts" on public.entry_posts;
create policy "Owners delete own entry posts"
  on public.entry_posts for delete
  using (auth.uid() = user_id);

drop policy if exists "Public read leaderboard scores" on public.leaderboard_scores;
create policy "Public read leaderboard scores"
  on public.leaderboard_scores for select
  using (true);

drop policy if exists "Authenticated insert leaderboard scores" on public.leaderboard_scores;
create policy "Authenticated insert leaderboard scores"
  on public.leaderboard_scores for insert
  with check (auth.role() = 'authenticated');

drop policy if exists "Authenticated update leaderboard scores" on public.leaderboard_scores;
create policy "Authenticated update leaderboard scores"
  on public.leaderboard_scores for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Authenticated delete leaderboard scores" on public.leaderboard_scores;
create policy "Authenticated delete leaderboard scores"
  on public.leaderboard_scores for delete
  using (auth.role() = 'authenticated');

drop policy if exists "Public read practice notes" on public.practice_day_subject_notes;
create policy "Public read practice notes"
  on public.practice_day_subject_notes for select
  using (true);

drop policy if exists "Public insert practice notes" on public.practice_day_subject_notes;
drop policy if exists "Authenticated insert own practice notes" on public.practice_day_subject_notes;
create policy "Authenticated insert own practice notes"
  on public.practice_day_subject_notes for insert
  with check (auth.uid() = user_id);

drop policy if exists "Owners update own practice notes" on public.practice_day_subject_notes;
create policy "Owners update own practice notes"
  on public.practice_day_subject_notes for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Owners delete own practice notes" on public.practice_day_subject_notes;
create policy "Owners delete own practice notes"
  on public.practice_day_subject_notes for delete
  using (auth.uid() = user_id);

create table if not exists public.home_posts (
  id bigint generated by default as identity primary key,
  content text not null,
  category text not null default 'Announcement',
  author text not null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.home_posts enable row level security;

drop policy if exists "Public read home posts" on public.home_posts;
create policy "Public read home posts"
  on public.home_posts for select
  using (true);

drop policy if exists "Authenticated insert own home posts" on public.home_posts;
create policy "Authenticated insert own home posts"
  on public.home_posts for insert
  with check (auth.uid() = user_id);

drop policy if exists "Owners delete own home posts" on public.home_posts;
create policy "Owners delete own home posts"
  on public.home_posts for delete
  using (auth.uid() = user_id);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  subject text not null,
  title text not null,
  description text,
  url text,
  file_type text not null default 'Document',
  author text not null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.resources enable row level security;

drop policy if exists "Public read resources" on public.resources;
create policy "Public read resources"
  on public.resources for select
  using (true);

drop policy if exists "Authenticated insert own resources" on public.resources;
create policy "Authenticated insert own resources"
  on public.resources for insert
  with check (auth.uid() = user_id);

drop policy if exists "Owners delete own resources" on public.resources;
create policy "Owners delete own resources"
  on public.resources for delete
  using (auth.uid() = user_id);

alter table public.home_posts
  add column if not exists image_url text;

create table if not exists public.assigned_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  subject text not null default 'General',
  priority text not null default 'Medium',
  due_date text,
  author text not null,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.assigned_tasks enable row level security;

drop policy if exists "Public read assigned tasks" on public.assigned_tasks;
create policy "Public read assigned tasks"
  on public.assigned_tasks for select
  using (true);

drop policy if exists "Authenticated insert assigned tasks" on public.assigned_tasks;
create policy "Authenticated insert assigned tasks"
  on public.assigned_tasks for insert
  with check (auth.uid() = user_id);

drop policy if exists "Owners delete assigned tasks" on public.assigned_tasks;
create policy "Owners delete assigned tasks"
  on public.assigned_tasks for delete
  using (auth.uid() = user_id);

-- Storage bucket for post thumbnail images.
insert into storage.buckets (id, name, public)
  values ('post-images', 'post-images', true)
  on conflict (id) do nothing;

drop policy if exists "Public read post images" on storage.objects;
create policy "Public read post images"
  on storage.objects for select
  using (bucket_id = 'post-images');

drop policy if exists "Authenticated upload post images" on storage.objects;
create policy "Authenticated upload post images"
  on storage.objects for insert
  with check (bucket_id = 'post-images' and auth.role() = 'authenticated');

alter table public.leaderboard_scores
  add column if not exists category text not null default 'main';

-- Seed the official squad roster (scores start at 0 and are updated via the admin panel).
insert into public.leaderboard_scores
  (student, overall, physics, chemistry, biology, mathematics, gk, category)
values
  ('Fabian Kudoto',        0, 0, 0, 0, 0, 0, 'main'),
  ('Norbert Adusei',       0, 0, 0, 0, 0, 0, 'main'),
  ('Emmanuel Akormedie',   0, 0, 0, 0, 0, 0, 'main'),
  ('Princess Amedzro',     0, 0, 0, 0, 0, 0, 'main'),
  ('Japheth Nii Boye',     0, 0, 0, 0, 0, 0, 'main'),
  ('Michael Danso',        0, 0, 0, 0, 0, 0, 'main'),
  ('Hilarious Bansah',     0, 0, 0, 0, 0, 0, 'main'),
  ('Prince Gewalk Martins',0, 0, 0, 0, 0, 0, 'main'),
  ('Jovan Akuaku',         0, 0, 0, 0, 0, 0, 'substitute'),
  ('Vera Narh',            0, 0, 0, 0, 0, 0, 'substitute'),
  ('Ann Hanson',           0, 0, 0, 0, 0, 0, 'substitute'),
  ('George Frimpong',      0, 0, 0, 0, 0, 0, 'substitute'),
  ('Clifford Anum',        0, 0, 0, 0, 0, 0, 'substitute')
on conflict do nothing;
